### PR TITLE
New bs theme

### PR DESCRIPTION
**Pull request by arunoda**
Here we use bootstrap and a new theme.

### CODE REVIEW

**Comment by mnmtanish** [comment]
https://github.com/kadirahq/storybook-builder/pull/21 will fix the storybook-builder issue.
It will show the error message instead of a blank page.

**Comment by arunoda** [comment]
@mnmtanish Thanks.
I also fix the real issue too.

**Comment by thinkholic** [comment]
@arunoda Homepage is done.

**Comment by thinkholic** [comment]
@arunoda Updated.

**Comment by thinkholic** [comment]
@arunoda Fixed alignment issue.

**Pull request merged**
