### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by arunoda**
Try to implement these components based on the notes I've added next to stories.

### CODE REVIEW

**Comment by arunoda** [comment]
@mnmtanish there's some issues in building this. Could you try that out.
Images not showing is related to the URL path. That can be fixed somehow, may be by running a separate domain.

**Comment by thinkholic** [comment]
@arunoda Can I get the original design to determine actual sizes?

**Comment by arunoda** [comment]
This font I suggest looks horrible here :) 
Go back to the arial.

Also change icons in the links to from glyphicons except for the slack.

**Comment by thinkholic** [comment]
@arunoda okay.

**Comment by arunoda** [comment]
Indi, currently there's fixed width for components. Try to make it responsive. 

There's already reflexbox available in this repo. Use it.

**Comment by arunoda** [comment]
Implemented a potential solution via #6

**Pull request closed without merging**
