### PR TITLE
Add a link to edit docs. #30

### LINKED ISSUE #30: Add a link to edit docs.
In every docs page, we need to add a link saying edit this document. Which send user to this repo and the correct file.

### PR DESCRIPTION
**Pull request by thinkholic**
Fixes #30

### CODE REVIEW

**Comment by arunoda** [comment]
Does this works with #43 ?

**Comment by thinkholic** [comment]
Yes. I make a branch from it.

**Comment by arunoda** [comment]
@thinkholic I merged this one.
But it's not showing the edit link.
Could you check the master?

**Comment by thinkholic** [comment]
@arunoda Fix #46

**Pull request merged**
