### PR TITLE
Implement docs section UI

### PR DESCRIPTION
**Pull request by arunoda**
I've added some design stories for the docs section with some notes.
@thinkholic could you implement these.

These also need to be responsive.
For the responsive theme, we can use some native select boxes as the navigation.

Related: #12

### CODE REVIEW

**Comment by thinkholic** [comment]
@arunoda Noted.

**Comment by thinkholic** [comment]
Header Note is;
//For the logo, use the the logo component used in the homepage.
But use a use CSS zoom property to scale it down.
May be you can use CSS transform too.//

But the design has no logo it seems.??

**Comment by arunoda** [comment]
Oops. Try to update react-storybook version. Get the latest. Fix a bug :)

**Comment by thinkholic** [comment]
@arunoda Okay

**Comment by arunoda** [comment]
I've merged this.
But there's no logo in the Header. Try to add that only for the Docs section.

**Pull request merged**
